export const TP_SERVER_ADDRESS = process.env.TP_SERVER_ADDRESS;

export const TP_TENANT_ADMIN_ID = process.env.TP_TENANT_ADMIN_ID;
export const TP_TENANT_ADMIN_PASSWORD = process.env.TP_TENANT_ADMIN_PASSWORD;

export const TP_IFLOWHVAC_MANAGER_CUSTOMTER_ID =
  process.env.TP_IFLOWHVAC_MANAGER_CUSTOMTER_ID;
export const TP_IFLOHVAC_UNREGISTERED_DEVICES_CUSTOMER_ID =
  process.env.TP_IFLOHVAC_UNREGISTERED_DEVICES_CUSTOMER_ID;
export const TP_IFLOWHVAC_GUEST_HOMEOWNER_MANAGER_CUSTOMER_ID =
  process.env.TP_IFLOWHVAC_GUEST_HOMEOWNER_MANAGER_CUSTOMER_ID;
export const TP_IFLOWHVAC_UNKNOWN_CONTRACTOR_CUSTOMER_ID =
  process.env.TP_IFLOWHVAC_UNKNOWN_CONTRACTOR_CUSTOMER_ID;
